SELECT apellido1, apellido2, nombre FROM persona WHERE tipo = 'alumno' ORDER BY apellido1, apellido2, nombre;
SELECT apellido1, apellido2, nombre FROM persona WHERE tipo = 'alumno' and telefono IS NULL;
SELECT * FROM persona WHERE tipo = 'alumno' AND fecha_nacimiento LIKE "1999%";
SELECT apellido1, apellido2, nombre, nif FROM persona WHERE tipo = 'profesor' and telefono IS NULL AND nif LIKE "%K";
SELECT * FROM asignatura WHERE cuatrimestre = 1 AND curso = 3 AND id_grado = 7;
SELECT apellido1, apellido2, pers.nombre, dep.nombre FROM persona pers JOIN profesor pro ON pers.id = pro.id_profesor JOIN departamento dep ON dep.id = pro.id_departamento ORDER BY apellido1, apellido2, pers.nombre;
SELECT asig.nombre, curso.anyo_inicio, curso.anyo_fin FROM persona pers JOIN alumno_se_matricula_asignatura ON pers.id = id_alumno JOIN curso_escolar curso ON curso.id = id_curso_escolar JOIN asignatura asig ON asig.id = id_asignatura WHERE pers.nif = '26902806M';
SELECT DISTINCT dep.nombre FROM departamento dep JOIN profesor pers ON pers.id_departamento = dep.id JOIN asignatura asig ON asig.id_profesor = pers.id_profesor JOIN grado gr ON gr.id = asig.id_grado WHERE gr.nombre = 'Grado en Ingeniería Informática (Plan 2015)';
SELECT curso.anyo_inicio, COUNT(distinct id_alumno) AS alumnes FROM curso_escolar curso JOIN alumno_se_matricula_asignatura asig ON asig.id_curso_escolar = curso.id GROUP BY curso.id;
SELECT dep.nombre, pers.apellido1, pers.apellido2, pers.nombre FROM persona pers RIGHT JOIN profesor pro ON pers.id = pro.id_profesor RIGHT JOIN departamento dep ON pro.id_departamento = dep.id WHERE pers.tipo = 'profesor' ORDER BY dep.nombre, pers.apellido1, pers.apellido2, pers.nombre;
SELECT * FROM persona RIGHT JOIN profesor ON id = id_profesor WHERE tipo = 'profesor' AND id_profesor IS NULL;
SELECT dep.nombre Departamento FROM departamento dep LEFT JOIN profesor pro ON dep.id = pro.id_departamento WHERE pro.id_departamento IS NULL;
SELECT pers.nombre Profesor FROM persona pers LEFT JOIN asignatura asig  ON pers.id = asig.id_profesor  LEFT JOIN profesor pro ON pers.id = pro.id_profesor  WHERE asig.id_profesor is NULL AND pers.tipo = "profesor"; 
SELECT id, nombre FROM asignatura WHERE id_profesor IS NULL;
SELECT DISTINCT dep.nombre Departamento FROM profesor pro RIGHT JOIN departamento dep ON pro.id_departamento = dep.id LEFT JOIN asignatura asig ON pro.id_profesor = asig.id_profesor WHERE asig.id_profesor IS NULL;
SELECT COUNT(*) FROM persona  WHERE tipo = 'alumno';
SELECT COUNT(*) FROM persona WHERE tipo = 'alumno' AND YEAR(fecha_nacimiento) = 1999;
 SELECT nombre AS Departament, COUNT(*) AS n_professors FROM departamento JOIN profesor ON id = id_departamento GROUP BY id ORDER BY n_professors DESC;
 SELECT nombre, COUNT(id_profesor) FROM departamento RIGHT JOIN profesor ON id = id_departamento GROUP BY id;
SELECT gr.nombre AS grau, COUNT(asig.id_grado) AS assignatures FROM asignatura asig RIGHT JOIN grado gr ON asig.id_grado = gr.id GROUP BY grau ORDER BY assignatures DESC;
SELECT gr.nombre  AS grau, COUNT(*) AS num_assignatures FROM grado gr JOIN asignatura asig ON asig.id_grado = gr.id GROUP BY gr.id HAVING num_assignatures > 40;
SELECT gr.nombre AS nom_grau, asig.tipo AS tipus, SUM(asig.creditos) AS credits FROM grado gr JOIN asignatura asig ON asig.id_grado = gr.id GROUP BY asig.tipo, gr.id;
 SELECT curso.anyo_inicio, COUNT(distinct id_alumno) AS alumnes FROM curso_escolar curso JOIN alumno_se_matricula_asignatura asig ON asig.id_curso_escolar = curso.id GROUP BY curso.id;
SELECT pers.id, pers.nombre, pers.apellido1, pers.apellido2, COUNT(asig.id) AS assignatures FROM persona pers LEFT JOIN asignatura asig ON pers.id = asig.id_profesor GROUP BY pers.id;
SELECT * FROM persona WHERE tipo = 'alumno' ORDER BY fecha_nacimiento DESC LIMIT 1;
SELECT pers.tipo, pers.nombre, pers.apellido1, pers.apellido2, asig.id AS asignatura, dep.nombre AS departamento FROM persona pers JOIN profesor pro ON pers.id = pro.id_profesor JOIN departamento dep ON dep.id = pro.id_departamento LEFT JOIN asignatura asig ON pro.id_profesor = asig.id_profesor WHERE asig.id is NULL;